### ISSUE TITLE
Use non-dev geni-lib

### ISSUE THREAD

**Issue by nbastin** [ivotron/docker-geni-lib#2]
Packaged and released versions of geni-lib are available via pypi - https://pypi.org/project/geni-lib/ - it would be better to use those via pip than cloning the 0.9-DEV branch from the repo (it should be stable, but mistakes happen sometimes).

**Comment by ivotron** [comment]
@nbastin I don't remember why we were installing from source. Now image is built by installing from using `pip`. Thanks a lot!

**Comment by nbastin** [comment]
I suspect the answer is because the project pre-dates the availability of geni-lib on pypi.. :-)

**Comment by ivotron** [comment]
Yeah, that's what I thought but I wasn't sure. Thanks!
